version: '1.0'
services:
  squid:
    container_name: squid
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - /squid.conf:/etc/squid/squid.conf
      - /srv/docker/squid/cache:/var/spool/squid
